using AMS.Model.Models;
using AMS_SCHEMA.Class;

namespace AMS.Model
{
    public class EntityBaseClassDefXx
    {
        public static readonly Dictionary<string, PropDef> PropertiesDict = new()
        {
            ["Title"] = new() { Type = "string", Description = "عنوان" },
            ["Name"] = new() { Type = "string", Description = "نام سیستمی" },
            ["Id"] = new() { Type = "Guid", Description = "شناسه موجودیت" },
            ["DisplayName"] = new() { Type = "string", Description = "نام نمایشی" },
            ["Description"] = new() { Type = "string", Description = "توضیحات" },
            ["ClientDomainName"] = new() { Type = "string", Description = "دامنه استفاده کاربر" },
            ["CreatedAt"] = new() { Type = "DateTime", Description = "ایجاد شده در تاریخ" },
            ["CreatedBy"] = new() { Type = "Guid", Description = "ایجاد شده توسط" },
            ["ModifiedAt"] = new() { Type = "DateTime", Description = "ویرایش شده در تاریخ" },
            ["ModifiedBy"] = new() { Type = "Guid", Description = "ویرایش شده توسط" },
            ["ModifyAction"] = new() { Type = "string", Description = "علت ایجاد تغییر" },
            ["TransactionLog"] = new() { Type = "string", Description = "لاگ تراکنش" },
            ["IsSoftDeleted"] = new() { Type = "bool", Description = "حذف شده؟" },
            ["SoftDeletedWhen"] = new() { Type = "DateTime", Description = "زمان حذف" },
            ["IsArchived"] = new() { Type = "bool", Description = "آرشیو شده؟" },
            ["ArchivedWhen"] = new() { Type = "DateTime", Description = "زمان بایگانی" },
            ["RowAccessPermission"] = new() { Type = "string", Description = "قوانین دسترسی به این رکورد" },
        };

        public static string[] DataTypes => new[]
        {
            "bool",
            "long",
            "int",
            "float",
            "sbyte",
            "short",
            "DateTime",
            "decimal",
            "double",
            "char",
            "Guid",
            "object",
            "List<string>",
            "List<bool>",
            "List<long>",
            "List<int>",
            "List<float>",
            "List<sbyte>",
            "List<short>",
            "List<DateTime>",
            "List<decimal>",
            "List<double>",
            "List<char>",
            "List<Guid>",
            "List<object>",
            "Dictionary<string,string>",
            "Dictionary<string,bool>",
            "Dictionary<string,long>",
            "Dictionary<string,int>",
            "Dictionary<string,float>",
            "Dictionary<string,sbyte>",
            "Dictionary<string,short>",
            "Dictionary<string,DateTime>",
            "Dictionary<string,decimal>",
            "Dictionary<string,double>",
            "Dictionary<string,char>",
            "Dictionary<string,Guid>",
            "Dictionary<string,object>",
            "Dictionary<bool,string>",
            "Dictionary<bool,bool>",
            "Dictionary<bool,long>",
            "Dictionary<bool,int>",
            "Dictionary<bool,float>",
            "Dictionary<bool,sbyte>",
            "Dictionary<bool,short>",
            "Dictionary<bool,DateTime>",
            "Dictionary<bool,decimal>",
            "Dictionary<bool,double>",
            "Dictionary<bool,char>",
            "Dictionary<bool,Guid>",
            "Dictionary<bool,object>",
            "Dictionary<long,string>",
            "Dictionary<long,bool>",
            "Dictionary<long,long>",
            "Dictionary<long,int>",
            "Dictionary<long,float>",
            "Dictionary<long,sbyte>",
            "Dictionary<long,short>",
            "Dictionary<long,DateTime>",
            "Dictionary<long,decimal>",
            "Dictionary<long,double>",
            "Dictionary<long,char>",
            "Dictionary<long,Guid>",
            "Dictionary<long,object>",
            "Dictionary<int,string>",
            "Dictionary<int,bool>",
            "Dictionary<int,long>",
            "Dictionary<int,int>",
            "Dictionary<int,float>",
            "Dictionary<int,sbyte>",
            "Dictionary<int,short>",
            "Dictionary<int,DateTime>",
            "Dictionary<int,decimal>",
            "Dictionary<int,double>",
            "Dictionary<int,char>",
            "Dictionary<int,Guid>",
            "Dictionary<int,object>",
            "Dictionary<float,string>",
            "Dictionary<float,bool>",
            "Dictionary<float,long>",
            "Dictionary<float,int>",
            "Dictionary<float,float>",
            "Dictionary<float,sbyte>",
            "Dictionary<float,short>",
            "Dictionary<float,DateTime>",
            "Dictionary<float,decimal>",
            "Dictionary<float,double>",
            "Dictionary<float,char>",
            "Dictionary<float,Guid>",
            "Dictionary<float,object>",
            "Dictionary<sbyte,string>",
            "Dictionary<sbyte,bool>",
            "Dictionary<sbyte,long>",
            "Dictionary<sbyte,int>",
            "Dictionary<sbyte,float>",
            "Dictionary<sbyte,sbyte>",
            "Dictionary<sbyte,short>",
            "Dictionary<sbyte,DateTime>",
            "Dictionary<sbyte,decimal>",
            "Dictionary<sbyte,double>",
            "Dictionary<sbyte,char>",
            "Dictionary<sbyte,Guid>",
            "Dictionary<sbyte,object>",
            "Dictionary<short,string>",
            "Dictionary<short,bool>",
            "Dictionary<short,long>",
            "Dictionary<short,int>",
            "Dictionary<short,float>",
            "Dictionary<short,sbyte>",
            "Dictionary<short,short>",
            "Dictionary<short,DateTime>",
            "Dictionary<short,decimal>",
            "Dictionary<short,double>",
            "Dictionary<short,char>",
            "Dictionary<short,Guid>",
            "Dictionary<short,object>",
            "Dictionary<DateTime,string>",
            "Dictionary<DateTime,bool>",
            "Dictionary<DateTime,long>",
            "Dictionary<DateTime,int>",
            "Dictionary<DateTime,float>",
            "Dictionary<DateTime,sbyte>",
            "Dictionary<DateTime,short>",
            "Dictionary<DateTime,DateTime>",
            "Dictionary<DateTime,decimal>",
            "Dictionary<DateTime,double>",
            "Dictionary<DateTime,char>",
            "Dictionary<DateTime,Guid>",
            "Dictionary<DateTime,object>",
            "Dictionary<decimal,string>",
            "Dictionary<decimal,bool>",
            "Dictionary<decimal,long>",
            "Dictionary<decimal,int>",
            "Dictionary<decimal,float>",
            "Dictionary<decimal,sbyte>",
            "Dictionary<decimal,short>",
            "Dictionary<decimal,DateTime>",
            "Dictionary<decimal,decimal>",
            "Dictionary<decimal,double>",
            "Dictionary<decimal,char>",
            "Dictionary<decimal,Guid>",
            "Dictionary<decimal,object>",
            "Dictionary<double,string>",
            "Dictionary<double,bool>",
            "Dictionary<double,long>",
            "Dictionary<double,int>",
            "Dictionary<double,float>",
            "Dictionary<double,sbyte>",
            "Dictionary<double,short>",
            "Dictionary<double,DateTime>",
            "Dictionary<double,decimal>",
            "Dictionary<double,double>",
            "Dictionary<double,char>",
            "Dictionary<double,Guid>",
            "Dictionary<double,object>",
            "Dictionary<char,string>",
            "Dictionary<char,bool>",
            "Dictionary<char,long>",
            "Dictionary<char,int>",
            "Dictionary<char,float>",
            "Dictionary<char,sbyte>",
            "Dictionary<char,short>",
            "Dictionary<char,DateTime>",
            "Dictionary<char,decimal>",
            "Dictionary<char,double>",
            "Dictionary<char,char>",
            "Dictionary<char,Guid>",
            "Dictionary<char,object>",
            "Dictionary<Guid,string>",
            "Dictionary<Guid,bool>",
            "Dictionary<Guid,long>",
            "Dictionary<Guid,int>",
            "Dictionary<Guid,float>",
            "Dictionary<Guid,sbyte>",
            "Dictionary<Guid,short>",
            "Dictionary<Guid,DateTime>",
            "Dictionary<Guid,decimal>",
            "Dictionary<Guid,double>",
            "Dictionary<Guid,char>",
            "Dictionary<Guid,Guid>",
            "Dictionary<Guid,object>",
            "Dictionary<object,string>",
            "Dictionary<object,bool>",
            "Dictionary<object,long>",
            "Dictionary<object,int>",
            "Dictionary<object,float>",
            "Dictionary<object,sbyte>",
            "Dictionary<object,short>",
            "Dictionary<object,DateTime>",
            "Dictionary<object,decimal>",
            "Dictionary<object,double>",
            "Dictionary<object,char>",
            "Dictionary<object,Guid>",
            "Dictionary<object,object>"
        };

        public static IEnumerable<AmsNeo4JNodeLabelProperty> Properties => GetEntityBaseProperties();

        public static IEnumerable<AmsNeo4JNodeLabelProperty> GetProperties(AmsNeo4JNodeLabel label)
        {
            return GetEntityBaseProperties(label);
        }

        public static IEnumerable<AmsNeo4JNodeLabelProperty> GetEntityBaseProperties(AmsNeo4JNodeLabel? label = null)
        {

            var props = PropertiesDict
                .Select(prop => new AmsNeo4JNodeLabelProperty
                {
                    Label = label,
                    Name = prop.Key,
                    Neo4jName = prop.Key.ToCamelCase(),
                    DataType = prop.Value.Type,
                    DisplayName = prop.Value.Description
                })
                .ToList();
            return props;

        }
    }

    public class PropDef
    {
        public string Type { get; set; }
        public string Description { get; set; }
    }
}
